### ISSUE TITLE
This was a great post

### ISSUE THREAD

**Issue by fabriziogiordano** [bclarkson-code/bclarkson-code.github.io#1]
This is not an issue but just a way to let you know you blog post llm-from-scratch-scalar-autograd post was amazing!
How do I get updated on the next post?

**Comment by bclarkson-code** [comment]
Thanks! I really appreciate it. I'm working on getting an RSS feed (and maybe a mailing list, not sure yet) set up, but in the mean time, if you follow this repo, i'll update the master branch whenever I finish a new post.

**Comment by bclarkson-code** [comment]
Oh, and you can follow my twitter/X: https://twitter.com/bclarkson_code

**Comment by bclarkson-code** [comment]
Also, also, i've put it on substack (if you subscribe you'll be notified the next time one comes out)
